/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module op_code_enum_7 (
    output reg [5:0] add,
    output reg [5:0] sub,
    output reg [5:0] mul,
    output reg [5:0] div,
    output reg [5:0] mod,
    output reg [5:0] and,
    output reg [5:0] or,
    output reg [5:0] xor,
    output reg [5:0] t_a,
    output reg [5:0] nand,
    output reg [5:0] nor,
    output reg [5:0] xnor,
    output reg [5:0] t_b,
    output reg [5:0] shl,
    output reg [5:0] shr,
    output reg [5:0] sra,
    output reg [5:0] eq,
    output reg [5:0] lt,
    output reg [5:0] ltq
  );
  
  
  
  always @* begin
    add = 6'h00;
    sub = 6'h01;
    mul = 6'h04;
    div = 6'h05;
    mod = 6'h06;
    and = 6'h18;
    or = 6'h1e;
    xor = 6'h16;
    t_a = 6'h1a;
    nand = 6'h17;
    nor = 6'h11;
    xnor = 6'h19;
    t_b = 6'h1c;
    shl = 6'h20;
    shr = 6'h21;
    sra = 6'h23;
    eq = 6'h33;
    lt = 6'h35;
    ltq = 6'h37;
  end
endmodule
