/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module regfile_address_enum_8 (
    output reg [4:0] box00,
    output reg [4:0] box01,
    output reg [4:0] box02,
    output reg [4:0] box10,
    output reg [4:0] box11,
    output reg [4:0] box12,
    output reg [4:0] box20,
    output reg [4:0] box21,
    output reg [4:0] box22,
    output reg [4:0] pieces_remaining_small_p1,
    output reg [4:0] pieces_remaining_small_p2,
    output reg [4:0] pieces_remaining_med_p1,
    output reg [4:0] pieces_remaining_med_p2,
    output reg [4:0] pieces_remaining_large_p1,
    output reg [4:0] pieces_remaining_large_p2,
    output reg [4:0] selected_size_p1,
    output reg [4:0] selected_size_p2,
    output reg [4:0] winner,
    output reg [4:0] box_addr,
    output reg [4:0] temp1,
    output reg [4:0] temp2,
    output reg [4:0] temp3,
    output reg [4:0] temp4,
    output reg [4:0] temp5,
    output reg [4:0] temp6,
    output reg [4:0] temp7,
    output reg [4:0] temp8,
    output reg [4:0] temp9,
    output reg [4:0] temp10,
    output reg [4:0] temp11,
    output reg [4:0] temp12,
    output reg [4:0] temp13
  );
  
  
  
  always @* begin
    box00 = 5'h00;
    box01 = 5'h01;
    box02 = 5'h02;
    box10 = 5'h03;
    box11 = 5'h04;
    box12 = 5'h05;
    box20 = 5'h06;
    box21 = 5'h07;
    box22 = 5'h08;
    pieces_remaining_small_p1 = 5'h09;
    pieces_remaining_small_p2 = 5'h0a;
    pieces_remaining_med_p1 = 5'h0b;
    pieces_remaining_med_p2 = 5'h0c;
    pieces_remaining_large_p1 = 5'h0d;
    pieces_remaining_large_p2 = 5'h0e;
    selected_size_p1 = 5'h0f;
    selected_size_p2 = 5'h10;
    winner = 5'h11;
    box_addr = 5'h12;
    temp1 = 5'h13;
    temp2 = 5'h14;
    temp3 = 5'h15;
    temp4 = 5'h16;
    temp5 = 5'h17;
    temp6 = 5'h18;
    temp7 = 5'h19;
    temp8 = 5'h1a;
    temp9 = 5'h1b;
    temp10 = 5'h1c;
    temp11 = 5'h1d;
    temp12 = 5'h1e;
    temp13 = 5'h1f;
  end
endmodule
